#!/bin/bash
# /etc/init.d/scopeclock

start() {
    echo "Starting scopeclock" 
    amixer -q sset PCM,0 100% && /usr/local/bin/scopeclock &
}

stop() {
    echo "Stopping scopeclock"
    killall scopeclock & 
}
case "$1" in 
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop && start
        ;;
    *)
        echo "Usage: /etc/init.d/scopeclock start|stop|restart"
        exit 1
        ;;
esac

exit 0
